//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.21 at 09:49:19 PM AEDT 
//


package com.mentor.harness.schema.bridgesharness;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AssemblyTypeAttribute.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="AssemblyTypeAttribute"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&gt;
 *     &lt;enumeration value="StandardAssembly"/&gt;
 *     &lt;enumeration value="ConnectorAssembly"/&gt;
 *     &lt;enumeration value="InHouseAssembly"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "AssemblyTypeAttribute")
@XmlEnum
public enum AssemblyTypeAttribute {

    @XmlEnumValue("StandardAssembly")
    STANDARD_ASSEMBLY("StandardAssembly"),
    @XmlEnumValue("ConnectorAssembly")
    CONNECTOR_ASSEMBLY("ConnectorAssembly"),
    @XmlEnumValue("InHouseAssembly")
    IN_HOUSE_ASSEMBLY("InHouseAssembly");
    private final String value;

    AssemblyTypeAttribute(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AssemblyTypeAttribute fromValue(String v) {
        for (AssemblyTypeAttribute c: AssemblyTypeAttribute.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
