//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.21 at 09:49:19 PM AEDT 
//


package com.mentor.harness.schema.bridgesharness;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BaseWireConnectionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BaseWireConnectionType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.mentor.com/harness/Schema/bridgesharness}BaseConnectionType"&gt;
 *       &lt;attribute name="materialcode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="terminalpartspec" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="sealpartspec" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BaseWireConnectionType")
@XmlSeeAlso({
    HarnessWireEndType.class
})
public class BaseWireConnectionType
    extends BaseConnectionType
{

    @XmlAttribute(name = "materialcode")
    protected String materialcode;
    @XmlAttribute(name = "terminalpartspec")
    protected String terminalpartspec;
    @XmlAttribute(name = "sealpartspec")
    protected String sealpartspec;

    /**
     * Gets the value of the materialcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaterialcode() {
        return materialcode;
    }

    /**
     * Sets the value of the materialcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaterialcode(String value) {
        this.materialcode = value;
    }

    /**
     * Gets the value of the terminalpartspec property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTerminalpartspec() {
        return terminalpartspec;
    }

    /**
     * Sets the value of the terminalpartspec property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTerminalpartspec(String value) {
        this.terminalpartspec = value;
    }

    /**
     * Gets the value of the sealpartspec property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSealpartspec() {
        return sealpartspec;
    }

    /**
     * Sets the value of the sealpartspec property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSealpartspec(String value) {
        this.sealpartspec = value;
    }

}
