//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.21 at 09:49:19 PM AEDT 
//


package com.mentor.harness.schema.bridgesharness;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElements;
import jakarta.xml.bind.annotation.XmlID;
import jakarta.xml.bind.annotation.XmlIDREF;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for BundleType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BundleType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;group ref="{http://www.mentor.com/harness/Schema/bridgesharness}PropertyGroup"/&gt;
 *           &lt;element name="segments" type="{http://www.mentor.com/harness/Schema/bridgesharness}SegmentsType"/&gt;
 *           &lt;element name="marker" type="{http://www.mentor.com/harness/Schema/bridgesharness}BundleLocationType"/&gt;
 *         &lt;/choice&gt;
 *         &lt;element name="bundlejunctioninfo" type="{http://www.mentor.com/harness/Schema/bridgesharness}BundleJunctionInfoType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attGroup ref="{http://www.mentor.com/harness/Schema/bridgesharness}OriginAttributeGroup"/&gt;
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" /&gt;
 *       &lt;attribute name="elecid" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="bendRadius" type="{http://www.w3.org/2001/XMLSchema}double" /&gt;
 *       &lt;attribute name="bendRadiusRatio" type="{http://www.w3.org/2001/XMLSchema}double" /&gt;
 *       &lt;attribute name="bundleDiameter" type="{http://www.w3.org/2001/XMLSchema}double" /&gt;
 *       &lt;attribute name="widthWithInsulations" type="{http://www.w3.org/2001/XMLSchema}double" /&gt;
 *       &lt;attribute name="endNode" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" /&gt;
 *       &lt;attribute name="length" use="required" type="{http://www.w3.org/2001/XMLSchema}double" /&gt;
 *       &lt;attribute name="minLength" type="{http://www.w3.org/2001/XMLSchema}double" /&gt;
 *       &lt;attribute name="maxDiameter" type="{http://www.w3.org/2001/XMLSchema}double" /&gt;
 *       &lt;attribute name="state" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="displayName" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="shortdescription" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="section" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="startNode" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" /&gt;
 *       &lt;attribute name="optionexpression" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="collapseTo"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&gt;
 *             &lt;enumeration value="start"/&gt;
 *             &lt;enumeration value="end"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BundleType", propOrder = {
    "propertyAndVariantAndFunctionalvariant",
    "bundlejunctioninfo"
})
public class BundleType {

    @XmlElements({
        @XmlElement(name = "property", type = BasePropertyType.class),
        @XmlElement(name = "variant", type = BaseVarianceType.class),
        @XmlElement(name = "functionalvariant", type = FunctionalVariantType.class),
        @XmlElement(name = "productionvariant", type = ProductionVariantType.class),
        @XmlElement(name = "refedmodule", type = BaseReferredModuleType.class),
        @XmlElement(name = "segments", type = SegmentsType.class),
        @XmlElement(name = "marker", type = BundleLocationType.class)
    })
    protected List<Object> propertyAndVariantAndFunctionalvariant;
    protected BundleJunctionInfoType bundlejunctioninfo;
    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "elecid")
    protected String elecid;
    @XmlAttribute(name = "bendRadius")
    protected Double bendRadius;
    @XmlAttribute(name = "bendRadiusRatio")
    protected Double bendRadiusRatio;
    @XmlAttribute(name = "bundleDiameter")
    protected Double bundleDiameter;
    @XmlAttribute(name = "widthWithInsulations")
    protected Double widthWithInsulations;
    @XmlAttribute(name = "endNode", required = true)
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object endNode;
    @XmlAttribute(name = "length", required = true)
    protected double length;
    @XmlAttribute(name = "minLength")
    protected Double minLength;
    @XmlAttribute(name = "maxDiameter")
    protected Double maxDiameter;
    @XmlAttribute(name = "state")
    protected String state;
    @XmlAttribute(name = "displayName")
    protected String displayName;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "shortdescription")
    protected String shortdescription;
    @XmlAttribute(name = "section")
    @XmlSchemaType(name = "anySimpleType")
    protected String section;
    @XmlAttribute(name = "startNode", required = true)
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object startNode;
    @XmlAttribute(name = "optionexpression")
    protected String optionexpression;
    @XmlAttribute(name = "collapseTo")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String collapseTo;
    @XmlAttribute(name = "origin")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String origin;

    /**
     * Gets the value of the propertyAndVariantAndFunctionalvariant property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the propertyAndVariantAndFunctionalvariant property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPropertyAndVariantAndFunctionalvariant().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BasePropertyType }
     * {@link BaseVarianceType }
     * {@link FunctionalVariantType }
     * {@link ProductionVariantType }
     * {@link BaseReferredModuleType }
     * {@link SegmentsType }
     * {@link BundleLocationType }
     * 
     * 
     */
    public List<Object> getPropertyAndVariantAndFunctionalvariant() {
        if (propertyAndVariantAndFunctionalvariant == null) {
            propertyAndVariantAndFunctionalvariant = new ArrayList<Object>();
        }
        return this.propertyAndVariantAndFunctionalvariant;
    }

    /**
     * Gets the value of the bundlejunctioninfo property.
     * 
     * @return
     *     possible object is
     *     {@link BundleJunctionInfoType }
     *     
     */
    public BundleJunctionInfoType getBundlejunctioninfo() {
        return bundlejunctioninfo;
    }

    /**
     * Sets the value of the bundlejunctioninfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BundleJunctionInfoType }
     *     
     */
    public void setBundlejunctioninfo(BundleJunctionInfoType value) {
        this.bundlejunctioninfo = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the elecid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getElecid() {
        return elecid;
    }

    /**
     * Sets the value of the elecid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setElecid(String value) {
        this.elecid = value;
    }

    /**
     * Gets the value of the bendRadius property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getBendRadius() {
        return bendRadius;
    }

    /**
     * Sets the value of the bendRadius property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setBendRadius(Double value) {
        this.bendRadius = value;
    }

    /**
     * Gets the value of the bendRadiusRatio property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getBendRadiusRatio() {
        return bendRadiusRatio;
    }

    /**
     * Sets the value of the bendRadiusRatio property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setBendRadiusRatio(Double value) {
        this.bendRadiusRatio = value;
    }

    /**
     * Gets the value of the bundleDiameter property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getBundleDiameter() {
        return bundleDiameter;
    }

    /**
     * Sets the value of the bundleDiameter property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setBundleDiameter(Double value) {
        this.bundleDiameter = value;
    }

    /**
     * Gets the value of the widthWithInsulations property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getWidthWithInsulations() {
        return widthWithInsulations;
    }

    /**
     * Sets the value of the widthWithInsulations property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setWidthWithInsulations(Double value) {
        this.widthWithInsulations = value;
    }

    /**
     * Gets the value of the endNode property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getEndNode() {
        return endNode;
    }

    /**
     * Sets the value of the endNode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setEndNode(Object value) {
        this.endNode = value;
    }

    /**
     * Gets the value of the length property.
     * 
     */
    public double getLength() {
        return length;
    }

    /**
     * Sets the value of the length property.
     * 
     */
    public void setLength(double value) {
        this.length = value;
    }

    /**
     * Gets the value of the minLength property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMinLength() {
        return minLength;
    }

    /**
     * Sets the value of the minLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMinLength(Double value) {
        this.minLength = value;
    }

    /**
     * Gets the value of the maxDiameter property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMaxDiameter() {
        return maxDiameter;
    }

    /**
     * Sets the value of the maxDiameter property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMaxDiameter(Double value) {
        this.maxDiameter = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setState(String value) {
        this.state = value;
    }

    /**
     * Gets the value of the displayName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * Sets the value of the displayName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisplayName(String value) {
        this.displayName = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the shortdescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShortdescription() {
        return shortdescription;
    }

    /**
     * Sets the value of the shortdescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShortdescription(String value) {
        this.shortdescription = value;
    }

    /**
     * Gets the value of the section property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSection() {
        return section;
    }

    /**
     * Sets the value of the section property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSection(String value) {
        this.section = value;
    }

    /**
     * Gets the value of the startNode property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getStartNode() {
        return startNode;
    }

    /**
     * Sets the value of the startNode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setStartNode(Object value) {
        this.startNode = value;
    }

    /**
     * Gets the value of the optionexpression property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOptionexpression() {
        return optionexpression;
    }

    /**
     * Sets the value of the optionexpression property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOptionexpression(String value) {
        this.optionexpression = value;
    }

    /**
     * Gets the value of the collapseTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCollapseTo() {
        return collapseTo;
    }

    /**
     * Sets the value of the collapseTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCollapseTo(String value) {
        this.collapseTo = value;
    }

    /**
     * Gets the value of the origin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrigin() {
        return origin;
    }

    /**
     * Sets the value of the origin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrigin(String value) {
        this.origin = value;
    }

}
