//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.21 at 09:49:19 PM AEDT 
//


package com.mentor.harness.schema.bridgesharness;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElements;
import jakarta.xml.bind.annotation.XmlIDREF;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CarrierType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CarrierType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *         &lt;element name="interfaceref"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;attribute name="interfacerefid" type="{http://www.w3.org/2001/XMLSchema}IDREF" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="signalmapping" type="{http://www.mentor.com/harness/Schema/bridgesharness}SignalMappingType"/&gt;
 *         &lt;element name="messagemapping" type="{http://www.mentor.com/harness/Schema/bridgesharness}MessageMappingType"/&gt;
 *         &lt;element name="property" type="{http://www.mentor.com/harness/Schema/bridgesharness}BasePropertyType"/&gt;
 *       &lt;/choice&gt;
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="bandwidth" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="impltype" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="isDiscrete" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CarrierType", propOrder = {
    "interfacerefOrSignalmappingOrMessagemapping"
})
public class CarrierType {

    @XmlElements({
        @XmlElement(name = "interfaceref", type = CarrierType.Interfaceref.class),
        @XmlElement(name = "signalmapping", type = SignalMappingType.class),
        @XmlElement(name = "messagemapping", type = MessageMappingType.class),
        @XmlElement(name = "property", type = BasePropertyType.class)
    })
    protected List<Object> interfacerefOrSignalmappingOrMessagemapping;
    @XmlAttribute(name = "id")
    @XmlSchemaType(name = "anySimpleType")
    protected String id;
    @XmlAttribute(name = "name")
    @XmlSchemaType(name = "anySimpleType")
    protected String name;
    @XmlAttribute(name = "bandwidth")
    @XmlSchemaType(name = "anySimpleType")
    protected String bandwidth;
    @XmlAttribute(name = "type")
    @XmlSchemaType(name = "anySimpleType")
    protected String type;
    @XmlAttribute(name = "impltype")
    @XmlSchemaType(name = "anySimpleType")
    protected String impltype;
    @XmlAttribute(name = "isDiscrete")
    @XmlSchemaType(name = "anySimpleType")
    protected String isDiscrete;

    /**
     * Gets the value of the interfacerefOrSignalmappingOrMessagemapping property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the interfacerefOrSignalmappingOrMessagemapping property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInterfacerefOrSignalmappingOrMessagemapping().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CarrierType.Interfaceref }
     * {@link SignalMappingType }
     * {@link MessageMappingType }
     * {@link BasePropertyType }
     * 
     * 
     */
    public List<Object> getInterfacerefOrSignalmappingOrMessagemapping() {
        if (interfacerefOrSignalmappingOrMessagemapping == null) {
            interfacerefOrSignalmappingOrMessagemapping = new ArrayList<Object>();
        }
        return this.interfacerefOrSignalmappingOrMessagemapping;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the bandwidth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBandwidth() {
        return bandwidth;
    }

    /**
     * Sets the value of the bandwidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBandwidth(String value) {
        this.bandwidth = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the impltype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImpltype() {
        return impltype;
    }

    /**
     * Sets the value of the impltype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImpltype(String value) {
        this.impltype = value;
    }

    /**
     * Gets the value of the isDiscrete property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsDiscrete() {
        return isDiscrete;
    }

    /**
     * Sets the value of the isDiscrete property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsDiscrete(String value) {
        this.isDiscrete = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;attribute name="interfacerefid" type="{http://www.w3.org/2001/XMLSchema}IDREF" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Interfaceref {

        @XmlAttribute(name = "interfacerefid")
        @XmlIDREF
        @XmlSchemaType(name = "IDREF")
        protected Object interfacerefid;

        /**
         * Gets the value of the interfacerefid property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getInterfacerefid() {
            return interfacerefid;
        }

        /**
         * Sets the value of the interfacerefid property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setInterfacerefid(Object value) {
            this.interfacerefid = value;
        }

    }

}
