//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.21 at 09:49:19 PM AEDT 
//


package com.mentor.harness.schema.bridgesharness;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlIDREF;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 *                 Can be a seal or a contact.
 *             
 * 
 * <p>Java class for CavityComponentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CavityComponentType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.mentor.com/harness/Schema/bridgesharness}BaseCavityComponentType"&gt;
 *       &lt;attribute name="derivativeref" type="{http://www.w3.org/2001/XMLSchema}IDREF" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CavityComponentType")
public class CavityComponentType
    extends BaseCavityComponentType
{

    @XmlAttribute(name = "derivativeref")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object derivativeref;

    /**
     * Gets the value of the derivativeref property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getDerivativeref() {
        return derivativeref;
    }

    /**
     * Sets the value of the derivativeref property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setDerivativeref(Object value) {
        this.derivativeref = value;
    }

}
