//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.21 at 09:49:19 PM AEDT 
//


package com.mentor.harness.schema.bridgesharness;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElements;
import jakarta.xml.bind.annotation.XmlIDREF;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 *                 Connectors have pins, backshells and other additional components.  If they are part of a modular assembly they will have a relationship to their containing shell.
 *             
 * 
 * <p>Java class for ConnectorType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ConnectorType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.mentor.com/harness/Schema/bridgesharness}BaseConnectorType"&gt;
 *       &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *         &lt;element name="backshell" type="{http://www.mentor.com/harness/Schema/bridgesharness}BackshellType"/&gt;
 *         &lt;element name="pin" type="{http://www.mentor.com/harness/Schema/bridgesharness}CavityPinType"/&gt;
 *         &lt;element name="variantElement" type="{http://www.mentor.com/harness/Schema/bridgesharness}VariantElementType"/&gt;
 *         &lt;element name="addpart" type="{http://www.mentor.com/harness/Schema/bridgesharness}AdditionalComponentType"/&gt;
 *         &lt;element name="node" type="{http://www.mentor.com/harness/Schema/bridgesharness}NodeType"/&gt;
 *         &lt;element name="route" type="{http://www.mentor.com/harness/Schema/bridgesharness}ConnectorRouteType"/&gt;
 *         &lt;group ref="{http://www.mentor.com/harness/Schema/bridgesharness}CommonElementsGroup"/&gt;
 *         &lt;element name="KeywayDir" type="{http://www.mentor.com/harness/Schema/bridgesharness}Cartesian3DCoordinate" minOccurs="0"/&gt;
 *         &lt;element name="PlanarKeywayDir" type="{http://www.mentor.com/harness/Schema/bridgesharness}CartesianPointType" minOccurs="0"/&gt;
 *       &lt;/choice&gt;
 *       &lt;attGroup ref="{http://www.mentor.com/harness/Schema/bridgesharness}ConnectivityCommonAttributes"/&gt;
 *       &lt;attGroup ref="{http://www.mentor.com/harness/Schema/bridgesharness}IECNamingAttributes"/&gt;
 *       &lt;attGroup ref="{http://www.mentor.com/harness/Schema/bridgesharness}ConnectorCommonAttributes"/&gt;
 *       &lt;attGroup ref="{http://www.mentor.com/harness/Schema/bridgesharness}SupplierPartAttributes"/&gt;
 *       &lt;attGroup ref="{http://www.mentor.com/harness/Schema/bridgesharness}ArchitecturalAttributes"/&gt;
 *       &lt;attribute name="nodeid" type="{http://www.w3.org/2001/XMLSchema}IDREF" /&gt;
 *       &lt;attribute name="displayName" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="refined" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="terminalmaterial" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="materialcode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="sealed" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="plugged" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="greased" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="idc" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="assembly" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="incBom" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="datum" default="front"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&gt;
 *             &lt;enumeration value="front"/&gt;
 *             &lt;enumeration value="back"/&gt;
 *             &lt;enumeration value="terminal"/&gt;
 *             &lt;enumeration value="default"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="backshellplugged" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="backshellsealed" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="backshellOrient" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="keywayangle" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="elevatedkeywayangle" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="position" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="color" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="librarytypecode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="mate" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="matedharness" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="slotname" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConnectorType", propOrder = {
    "backshellOrPinOrVariantElement"
})
@XmlSeeAlso({
    ShellType.class
})
public class ConnectorType
    extends BaseConnectorType
{

    @XmlElements({
        @XmlElement(name = "backshell", type = BackshellType.class),
        @XmlElement(name = "pin", type = CavityPinType.class),
        @XmlElement(name = "variantElement", type = VariantElementType.class),
        @XmlElement(name = "addpart", type = AdditionalComponentType.class),
        @XmlElement(name = "node", type = NodeType.class),
        @XmlElement(name = "route", type = ConnectorRouteType.class),
        @XmlElement(name = "harnesslevel", type = HarnessLevelType.class),
        @XmlElement(name = "property", type = BasePropertyType.class),
        @XmlElement(name = "variant", type = BaseVarianceType.class),
        @XmlElement(name = "functionalvariant", type = FunctionalVariantType.class),
        @XmlElement(name = "productionvariant", type = ProductionVariantType.class),
        @XmlElement(name = "refedmodule", type = BaseReferredModuleType.class),
        @XmlElement(name = "KeywayDir", type = Cartesian3DCoordinate.class),
        @XmlElement(name = "PlanarKeywayDir", type = CartesianPointType.class)
    })
    protected List<Object> backshellOrPinOrVariantElement;
    @XmlAttribute(name = "nodeid")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object nodeid;
    @XmlAttribute(name = "displayName")
    protected String displayName;
    @XmlAttribute(name = "refined")
    protected Boolean refined;
    @XmlAttribute(name = "terminalmaterial")
    protected String terminalmaterial;
    @XmlAttribute(name = "materialcode")
    protected String materialcode;
    @XmlAttribute(name = "sealed")
    protected Boolean sealed;
    @XmlAttribute(name = "plugged")
    protected Boolean plugged;
    @XmlAttribute(name = "greased")
    protected Boolean greased;
    @XmlAttribute(name = "idc")
    protected Boolean idc;
    @XmlAttribute(name = "assembly")
    protected Boolean assembly;
    @XmlAttribute(name = "incBom")
    protected Boolean incBom;
    @XmlAttribute(name = "datum")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String datum;
    @XmlAttribute(name = "backshellplugged")
    protected Boolean backshellplugged;
    @XmlAttribute(name = "backshellsealed")
    protected Boolean backshellsealed;
    @XmlAttribute(name = "backshellOrient")
    protected String backshellOrient;
    @XmlAttribute(name = "keywayangle")
    protected String keywayangle;
    @XmlAttribute(name = "elevatedkeywayangle")
    protected String elevatedkeywayangle;
    @XmlAttribute(name = "position")
    protected String position;
    @XmlAttribute(name = "color")
    protected String color;
    @XmlAttribute(name = "librarytypecode")
    protected String librarytypecode;
    @XmlAttribute(name = "mate")
    protected String mate;
    @XmlAttribute(name = "matedharness")
    protected String matedharness;
    @XmlAttribute(name = "slotname")
    protected String slotname;
    @XmlAttribute(name = "harness")
    protected String harness;
    @XmlAttribute(name = "partnumber")
    protected String partnumber;
    @XmlAttribute(name = "partrevision")
    protected String partrevision;
    @XmlAttribute(name = "state")
    protected String state;
    @XmlAttribute(name = "function")
    protected String function;
    @XmlAttribute(name = "location")
    protected String location;
    @XmlAttribute(name = "shellid")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object shellid;
    @XmlAttribute(name = "origin")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String origin;
    @XmlAttribute(name = "supplierpart")
    @XmlSchemaType(name = "anySimpleType")
    protected String supplierpart;
    @XmlAttribute(name = "customerpart")
    @XmlSchemaType(name = "anySimpleType")
    protected String customerpart;
    @XmlAttribute(name = "architecturalCost")
    protected Double architecturalCost;
    @XmlAttribute(name = "weight")
    protected Double weight;

    /**
     * Gets the value of the backshellOrPinOrVariantElement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the backshellOrPinOrVariantElement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBackshellOrPinOrVariantElement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BackshellType }
     * {@link CavityPinType }
     * {@link VariantElementType }
     * {@link AdditionalComponentType }
     * {@link NodeType }
     * {@link ConnectorRouteType }
     * {@link HarnessLevelType }
     * {@link BasePropertyType }
     * {@link BaseVarianceType }
     * {@link FunctionalVariantType }
     * {@link ProductionVariantType }
     * {@link BaseReferredModuleType }
     * {@link Cartesian3DCoordinate }
     * {@link CartesianPointType }
     * 
     * 
     */
    public List<Object> getBackshellOrPinOrVariantElement() {
        if (backshellOrPinOrVariantElement == null) {
            backshellOrPinOrVariantElement = new ArrayList<Object>();
        }
        return this.backshellOrPinOrVariantElement;
    }

    /**
     * Gets the value of the nodeid property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getNodeid() {
        return nodeid;
    }

    /**
     * Sets the value of the nodeid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setNodeid(Object value) {
        this.nodeid = value;
    }

    /**
     * Gets the value of the displayName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * Sets the value of the displayName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisplayName(String value) {
        this.displayName = value;
    }

    /**
     * Gets the value of the refined property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRefined() {
        return refined;
    }

    /**
     * Sets the value of the refined property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRefined(Boolean value) {
        this.refined = value;
    }

    /**
     * Gets the value of the terminalmaterial property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTerminalmaterial() {
        return terminalmaterial;
    }

    /**
     * Sets the value of the terminalmaterial property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTerminalmaterial(String value) {
        this.terminalmaterial = value;
    }

    /**
     * Gets the value of the materialcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaterialcode() {
        return materialcode;
    }

    /**
     * Sets the value of the materialcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaterialcode(String value) {
        this.materialcode = value;
    }

    /**
     * Gets the value of the sealed property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSealed() {
        return sealed;
    }

    /**
     * Sets the value of the sealed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSealed(Boolean value) {
        this.sealed = value;
    }

    /**
     * Gets the value of the plugged property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPlugged() {
        return plugged;
    }

    /**
     * Sets the value of the plugged property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPlugged(Boolean value) {
        this.plugged = value;
    }

    /**
     * Gets the value of the greased property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isGreased() {
        return greased;
    }

    /**
     * Sets the value of the greased property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setGreased(Boolean value) {
        this.greased = value;
    }

    /**
     * Gets the value of the idc property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIdc() {
        return idc;
    }

    /**
     * Sets the value of the idc property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIdc(Boolean value) {
        this.idc = value;
    }

    /**
     * Gets the value of the assembly property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAssembly() {
        return assembly;
    }

    /**
     * Sets the value of the assembly property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAssembly(Boolean value) {
        this.assembly = value;
    }

    /**
     * Gets the value of the incBom property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIncBom() {
        return incBom;
    }

    /**
     * Sets the value of the incBom property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIncBom(Boolean value) {
        this.incBom = value;
    }

    /**
     * Gets the value of the datum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatum() {
        if (datum == null) {
            return "front";
        } else {
            return datum;
        }
    }

    /**
     * Sets the value of the datum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatum(String value) {
        this.datum = value;
    }

    /**
     * Gets the value of the backshellplugged property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isBackshellplugged() {
        return backshellplugged;
    }

    /**
     * Sets the value of the backshellplugged property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBackshellplugged(Boolean value) {
        this.backshellplugged = value;
    }

    /**
     * Gets the value of the backshellsealed property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isBackshellsealed() {
        return backshellsealed;
    }

    /**
     * Sets the value of the backshellsealed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBackshellsealed(Boolean value) {
        this.backshellsealed = value;
    }

    /**
     * Gets the value of the backshellOrient property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBackshellOrient() {
        return backshellOrient;
    }

    /**
     * Sets the value of the backshellOrient property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBackshellOrient(String value) {
        this.backshellOrient = value;
    }

    /**
     * Gets the value of the keywayangle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKeywayangle() {
        return keywayangle;
    }

    /**
     * Sets the value of the keywayangle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKeywayangle(String value) {
        this.keywayangle = value;
    }

    /**
     * Gets the value of the elevatedkeywayangle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getElevatedkeywayangle() {
        return elevatedkeywayangle;
    }

    /**
     * Sets the value of the elevatedkeywayangle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setElevatedkeywayangle(String value) {
        this.elevatedkeywayangle = value;
    }

    /**
     * Gets the value of the position property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPosition() {
        return position;
    }

    /**
     * Sets the value of the position property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPosition(String value) {
        this.position = value;
    }

    /**
     * Gets the value of the color property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColor() {
        return color;
    }

    /**
     * Sets the value of the color property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColor(String value) {
        this.color = value;
    }

    /**
     * Gets the value of the librarytypecode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLibrarytypecode() {
        return librarytypecode;
    }

    /**
     * Sets the value of the librarytypecode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLibrarytypecode(String value) {
        this.librarytypecode = value;
    }

    /**
     * Gets the value of the mate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMate() {
        return mate;
    }

    /**
     * Sets the value of the mate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMate(String value) {
        this.mate = value;
    }

    /**
     * Gets the value of the matedharness property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMatedharness() {
        return matedharness;
    }

    /**
     * Sets the value of the matedharness property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMatedharness(String value) {
        this.matedharness = value;
    }

    /**
     * Gets the value of the slotname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSlotname() {
        return slotname;
    }

    /**
     * Sets the value of the slotname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSlotname(String value) {
        this.slotname = value;
    }

    /**
     * Gets the value of the harness property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHarness() {
        return harness;
    }

    /**
     * Sets the value of the harness property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHarness(String value) {
        this.harness = value;
    }

    /**
     * Gets the value of the partnumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartnumber() {
        return partnumber;
    }

    /**
     * Sets the value of the partnumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartnumber(String value) {
        this.partnumber = value;
    }

    /**
     * Gets the value of the partrevision property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartrevision() {
        return partrevision;
    }

    /**
     * Sets the value of the partrevision property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartrevision(String value) {
        this.partrevision = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setState(String value) {
        this.state = value;
    }

    /**
     * Gets the value of the function property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFunction() {
        return function;
    }

    /**
     * Sets the value of the function property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFunction(String value) {
        this.function = value;
    }

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocation(String value) {
        this.location = value;
    }

    /**
     * Gets the value of the shellid property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getShellid() {
        return shellid;
    }

    /**
     * Sets the value of the shellid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setShellid(Object value) {
        this.shellid = value;
    }

    /**
     * Gets the value of the origin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrigin() {
        return origin;
    }

    /**
     * Sets the value of the origin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrigin(String value) {
        this.origin = value;
    }

    /**
     * Gets the value of the supplierpart property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupplierpart() {
        return supplierpart;
    }

    /**
     * Sets the value of the supplierpart property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupplierpart(String value) {
        this.supplierpart = value;
    }

    /**
     * Gets the value of the customerpart property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerpart() {
        return customerpart;
    }

    /**
     * Sets the value of the customerpart property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerpart(String value) {
        this.customerpart = value;
    }

    /**
     * Gets the value of the architecturalCost property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getArchitecturalCost() {
        return architecturalCost;
    }

    /**
     * Sets the value of the architecturalCost property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setArchitecturalCost(Double value) {
        this.architecturalCost = value;
    }

    /**
     * Gets the value of the weight property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getWeight() {
        return weight;
    }

    /**
     * Sets the value of the weight property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setWeight(Double value) {
        this.weight = value;
    }

}
