//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.21 at 09:49:19 PM AEDT 
//


package com.mentor.harness.schema.bridgesharness;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CriticalDimensionType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="CriticalDimensionType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&gt;
 *     &lt;enumeration value="standard"/&gt;
 *     &lt;enumeration value="reference"/&gt;
 *     &lt;enumeration value="external"/&gt;
 *     &lt;enumeration value="xaxial"/&gt;
 *     &lt;enumeration value="yaxial"/&gt;
 *     &lt;enumeration value="xyaxial"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "CriticalDimensionType")
@XmlEnum
public enum CriticalDimensionType {

    @XmlEnumValue("standard")
    STANDARD("standard"),
    @XmlEnumValue("reference")
    REFERENCE("reference"),
    @XmlEnumValue("external")
    EXTERNAL("external"),
    @XmlEnumValue("xaxial")
    XAXIAL("xaxial"),
    @XmlEnumValue("yaxial")
    YAXIAL("yaxial"),
    @XmlEnumValue("xyaxial")
    XYAXIAL("xyaxial");
    private final String value;

    CriticalDimensionType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CriticalDimensionType fromValue(String v) {
        for (CriticalDimensionType c: CriticalDimensionType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
