//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.21 at 09:49:19 PM AEDT 
//


package com.mentor.harness.schema.bridgesharness;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElements;
import jakarta.xml.bind.annotation.XmlID;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Represents a derivative of a composite harness.
 *             
 * 
 * <p>Java class for DerivativeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DerivativeType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;group ref="{http://www.mentor.com/harness/Schema/bridgesharness}PropertyGroup"/&gt;
 *           &lt;element name="scopeset" type="{http://www.mentor.com/harness/Schema/bridgesharness}BaseScopeSetType" minOccurs="0"/&gt;
 *           &lt;element name="optionref" type="{http://www.mentor.com/harness/Schema/bridgesharness}BaseOptionRefType"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *       &lt;attGroup ref="{http://www.mentor.com/harness/Schema/bridgesharness}DesignAttributeContainerType"/&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DerivativeType", propOrder = {
    "propertyAndVariantAndFunctionalvariant"
})
public class DerivativeType {

    @XmlElements({
        @XmlElement(name = "property", type = BasePropertyType.class),
        @XmlElement(name = "variant", type = BaseVarianceType.class),
        @XmlElement(name = "functionalvariant", type = FunctionalVariantType.class),
        @XmlElement(name = "productionvariant", type = ProductionVariantType.class),
        @XmlElement(name = "refedmodule", type = BaseReferredModuleType.class),
        @XmlElement(name = "scopeset", type = BaseScopeSetType.class),
        @XmlElement(name = "optionref", type = BaseOptionRefType.class)
    })
    protected List<Object> propertyAndVariantAndFunctionalvariant;
    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "description")
    protected String description;
    @XmlAttribute(name = "shortdesc")
    protected String shortdesc;
    @XmlAttribute(name = "revision")
    protected String revision;
    @XmlAttribute(name = "customerName")
    protected String customerName;
    @XmlAttribute(name = "customerRevision")
    protected String customerRevision;
    @XmlAttribute(name = "creationDate")
    protected String creationDate;
    @XmlAttribute(name = "customerCreationDate")
    protected String customerCreationDate;
    @XmlAttribute(name = "manufacturingSite")
    protected String manufacturingSite;
    @XmlAttribute(name = "userField1")
    protected String userField1;
    @XmlAttribute(name = "userField2")
    protected String userField2;
    @XmlAttribute(name = "userField3")
    protected String userField3;
    @XmlAttribute(name = "userField4")
    protected String userField4;
    @XmlAttribute(name = "userField5")
    protected String userField5;
    @XmlAttribute(name = "datum")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String datum;
    @XmlAttribute(name = "datumNode")
    protected String datumNode;
    @XmlAttribute(name = "datumRoute")
    protected String datumRoute;
    @XmlAttribute(name = "group")
    protected String group;
    @XmlAttribute(name = "sealedConnectors")
    protected Boolean sealedConnectors;
    @XmlAttribute(name = "pluggedConnectors")
    protected Boolean pluggedConnectors;
    @XmlAttribute(name = "insulatedSplices")
    protected Boolean insulatedSplices;
    @XmlAttribute(name = "releaseLevel")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String releaseLevel;
    @XmlAttribute(name = "releaseLevelName")
    protected String releaseLevelName;
    @XmlAttribute(name = "libraryScoped")
    protected Boolean libraryScoped;
    @XmlAttribute(name = "libScopedByType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String libScopedByType;
    @XmlAttribute(name = "objecttag")
    protected String objecttag;
    @XmlAttribute(name = "tubeaddontype")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String tubeaddontype;
    @XmlAttribute(name = "tubeaddonfactor")
    protected String tubeaddonfactor;
    @XmlAttribute(name = "manualterminal")
    protected Boolean manualterminal;
    @XmlAttribute(name = "usepitchtables")
    protected Boolean usepitchtables;
    @XmlAttribute(name = "supplierpart")
    @XmlSchemaType(name = "anySimpleType")
    protected String supplierpart;
    @XmlAttribute(name = "customerpart")
    @XmlSchemaType(name = "anySimpleType")
    protected String customerpart;
    @XmlAttribute(name = "partnumber")
    protected String partnumber;
    @XmlAttribute(name = "partrevision")
    protected String partrevision;
    @XmlAttribute(name = "incBom")
    protected Boolean incBom;
    @XmlAttribute(name = "librarytypecode")
    protected String librarytypecode;
    @XmlAttribute(name = "shortdescription")
    protected String shortdescription;
    @XmlAttribute(name = "architecturalCost")
    protected Double architecturalCost;
    @XmlAttribute(name = "weight")
    protected Double weight;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "displayName")
    protected String displayName;

    /**
     * Gets the value of the propertyAndVariantAndFunctionalvariant property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the propertyAndVariantAndFunctionalvariant property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPropertyAndVariantAndFunctionalvariant().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BasePropertyType }
     * {@link BaseVarianceType }
     * {@link FunctionalVariantType }
     * {@link ProductionVariantType }
     * {@link BaseReferredModuleType }
     * {@link BaseScopeSetType }
     * {@link BaseOptionRefType }
     * 
     * 
     */
    public List<Object> getPropertyAndVariantAndFunctionalvariant() {
        if (propertyAndVariantAndFunctionalvariant == null) {
            propertyAndVariantAndFunctionalvariant = new ArrayList<Object>();
        }
        return this.propertyAndVariantAndFunctionalvariant;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the shortdesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShortdesc() {
        return shortdesc;
    }

    /**
     * Sets the value of the shortdesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShortdesc(String value) {
        this.shortdesc = value;
    }

    /**
     * Gets the value of the revision property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRevision() {
        return revision;
    }

    /**
     * Sets the value of the revision property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRevision(String value) {
        this.revision = value;
    }

    /**
     * Gets the value of the customerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * Sets the value of the customerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerName(String value) {
        this.customerName = value;
    }

    /**
     * Gets the value of the customerRevision property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerRevision() {
        return customerRevision;
    }

    /**
     * Sets the value of the customerRevision property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerRevision(String value) {
        this.customerRevision = value;
    }

    /**
     * Gets the value of the creationDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreationDate() {
        return creationDate;
    }

    /**
     * Sets the value of the creationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreationDate(String value) {
        this.creationDate = value;
    }

    /**
     * Gets the value of the customerCreationDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerCreationDate() {
        return customerCreationDate;
    }

    /**
     * Sets the value of the customerCreationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerCreationDate(String value) {
        this.customerCreationDate = value;
    }

    /**
     * Gets the value of the manufacturingSite property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getManufacturingSite() {
        return manufacturingSite;
    }

    /**
     * Sets the value of the manufacturingSite property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setManufacturingSite(String value) {
        this.manufacturingSite = value;
    }

    /**
     * Gets the value of the userField1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserField1() {
        return userField1;
    }

    /**
     * Sets the value of the userField1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserField1(String value) {
        this.userField1 = value;
    }

    /**
     * Gets the value of the userField2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserField2() {
        return userField2;
    }

    /**
     * Sets the value of the userField2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserField2(String value) {
        this.userField2 = value;
    }

    /**
     * Gets the value of the userField3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserField3() {
        return userField3;
    }

    /**
     * Sets the value of the userField3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserField3(String value) {
        this.userField3 = value;
    }

    /**
     * Gets the value of the userField4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserField4() {
        return userField4;
    }

    /**
     * Sets the value of the userField4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserField4(String value) {
        this.userField4 = value;
    }

    /**
     * Gets the value of the userField5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserField5() {
        return userField5;
    }

    /**
     * Sets the value of the userField5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserField5(String value) {
        this.userField5 = value;
    }

    /**
     * Gets the value of the datum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatum() {
        if (datum == null) {
            return "front";
        } else {
            return datum;
        }
    }

    /**
     * Sets the value of the datum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatum(String value) {
        this.datum = value;
    }

    /**
     * Gets the value of the datumNode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatumNode() {
        return datumNode;
    }

    /**
     * Sets the value of the datumNode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatumNode(String value) {
        this.datumNode = value;
    }

    /**
     * Gets the value of the datumRoute property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatumRoute() {
        return datumRoute;
    }

    /**
     * Sets the value of the datumRoute property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatumRoute(String value) {
        this.datumRoute = value;
    }

    /**
     * Gets the value of the group property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroup() {
        return group;
    }

    /**
     * Sets the value of the group property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroup(String value) {
        this.group = value;
    }

    /**
     * Gets the value of the sealedConnectors property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSealedConnectors() {
        return sealedConnectors;
    }

    /**
     * Sets the value of the sealedConnectors property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSealedConnectors(Boolean value) {
        this.sealedConnectors = value;
    }

    /**
     * Gets the value of the pluggedConnectors property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPluggedConnectors() {
        return pluggedConnectors;
    }

    /**
     * Sets the value of the pluggedConnectors property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPluggedConnectors(Boolean value) {
        this.pluggedConnectors = value;
    }

    /**
     * Gets the value of the insulatedSplices property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isInsulatedSplices() {
        return insulatedSplices;
    }

    /**
     * Sets the value of the insulatedSplices property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setInsulatedSplices(Boolean value) {
        this.insulatedSplices = value;
    }

    /**
     * Gets the value of the releaseLevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReleaseLevel() {
        return releaseLevel;
    }

    /**
     * Sets the value of the releaseLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReleaseLevel(String value) {
        this.releaseLevel = value;
    }

    /**
     * Gets the value of the releaseLevelName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReleaseLevelName() {
        return releaseLevelName;
    }

    /**
     * Sets the value of the releaseLevelName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReleaseLevelName(String value) {
        this.releaseLevelName = value;
    }

    /**
     * Gets the value of the libraryScoped property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isLibraryScoped() {
        return libraryScoped;
    }

    /**
     * Sets the value of the libraryScoped property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLibraryScoped(Boolean value) {
        this.libraryScoped = value;
    }

    /**
     * Gets the value of the libScopedByType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLibScopedByType() {
        if (libScopedByType == null) {
            return "none";
        } else {
            return libScopedByType;
        }
    }

    /**
     * Sets the value of the libScopedByType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLibScopedByType(String value) {
        this.libScopedByType = value;
    }

    /**
     * Gets the value of the objecttag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObjecttag() {
        return objecttag;
    }

    /**
     * Sets the value of the objecttag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObjecttag(String value) {
        this.objecttag = value;
    }

    /**
     * Gets the value of the tubeaddontype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTubeaddontype() {
        if (tubeaddontype == null) {
            return "None";
        } else {
            return tubeaddontype;
        }
    }

    /**
     * Sets the value of the tubeaddontype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTubeaddontype(String value) {
        this.tubeaddontype = value;
    }

    /**
     * Gets the value of the tubeaddonfactor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTubeaddonfactor() {
        return tubeaddonfactor;
    }

    /**
     * Sets the value of the tubeaddonfactor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTubeaddonfactor(String value) {
        this.tubeaddonfactor = value;
    }

    /**
     * Gets the value of the manualterminal property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isManualterminal() {
        return manualterminal;
    }

    /**
     * Sets the value of the manualterminal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setManualterminal(Boolean value) {
        this.manualterminal = value;
    }

    /**
     * Gets the value of the usepitchtables property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUsepitchtables() {
        return usepitchtables;
    }

    /**
     * Sets the value of the usepitchtables property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUsepitchtables(Boolean value) {
        this.usepitchtables = value;
    }

    /**
     * Gets the value of the supplierpart property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupplierpart() {
        return supplierpart;
    }

    /**
     * Sets the value of the supplierpart property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupplierpart(String value) {
        this.supplierpart = value;
    }

    /**
     * Gets the value of the customerpart property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerpart() {
        return customerpart;
    }

    /**
     * Sets the value of the customerpart property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerpart(String value) {
        this.customerpart = value;
    }

    /**
     * Gets the value of the partnumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartnumber() {
        return partnumber;
    }

    /**
     * Sets the value of the partnumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartnumber(String value) {
        this.partnumber = value;
    }

    /**
     * Gets the value of the partrevision property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartrevision() {
        return partrevision;
    }

    /**
     * Sets the value of the partrevision property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartrevision(String value) {
        this.partrevision = value;
    }

    /**
     * Gets the value of the incBom property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIncBom() {
        return incBom;
    }

    /**
     * Sets the value of the incBom property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIncBom(Boolean value) {
        this.incBom = value;
    }

    /**
     * Gets the value of the librarytypecode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLibrarytypecode() {
        return librarytypecode;
    }

    /**
     * Sets the value of the librarytypecode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLibrarytypecode(String value) {
        this.librarytypecode = value;
    }

    /**
     * Gets the value of the shortdescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShortdescription() {
        return shortdescription;
    }

    /**
     * Sets the value of the shortdescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShortdescription(String value) {
        this.shortdescription = value;
    }

    /**
     * Gets the value of the architecturalCost property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getArchitecturalCost() {
        return architecturalCost;
    }

    /**
     * Sets the value of the architecturalCost property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setArchitecturalCost(Double value) {
        this.architecturalCost = value;
    }

    /**
     * Gets the value of the weight property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getWeight() {
        return weight;
    }

    /**
     * Sets the value of the weight property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setWeight(Double value) {
        this.weight = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the displayName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * Sets the value of the displayName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisplayName(String value) {
        this.displayName = value;
    }

}
