//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.21 at 09:49:19 PM AEDT 
//


package com.mentor.harness.schema.bridgesharness;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FlatteningConstraintElementType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FlatteningConstraintElementType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence maxOccurs="unbounded" minOccurs="0"&gt;
 *         &lt;element name="elementref" type="{http://www.mentor.com/harness/Schema/bridgesharness}ConstraintParameterType"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="value" type="{http://www.mentor.com/harness/Schema/bridgesharness}OrientationConstraintType" default="linear" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FlatteningConstraintElementType", propOrder = {
    "elementref"
})
public class FlatteningConstraintElementType {

    protected List<ConstraintParameterType> elementref;
    @XmlAttribute(name = "value")
    protected OrientationConstraintType value;

    /**
     * Gets the value of the elementref property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the elementref property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getElementref().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ConstraintParameterType }
     * 
     * 
     */
    public List<ConstraintParameterType> getElementref() {
        if (elementref == null) {
            elementref = new ArrayList<ConstraintParameterType>();
        }
        return this.elementref;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link OrientationConstraintType }
     *     
     */
    public OrientationConstraintType getValue() {
        if (value == null) {
            return OrientationConstraintType.LINEAR;
        } else {
            return value;
        }
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrientationConstraintType }
     *     
     */
    public void setValue(OrientationConstraintType value) {
        this.value = value;
    }

}
