//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.21 at 09:49:19 PM AEDT 
//


package com.mentor.harness.schema.bridgesharness;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElements;
import jakarta.xml.bind.annotation.XmlID;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for FunctionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FunctionType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *         &lt;element name="port"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;extension base="{http://www.mentor.com/harness/Schema/bridgesharness}PortType"&gt;
 *               &lt;/extension&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="property" type="{http://www.mentor.com/harness/Schema/bridgesharness}BasePropertyType"/&gt;
 *       &lt;/choice&gt;
 *       &lt;attGroup ref="{http://www.mentor.com/harness/Schema/bridgesharness}SymbolAttributes"/&gt;
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" /&gt;
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="architecturalCost" type="{http://www.w3.org/2001/XMLSchema}double" /&gt;
 *       &lt;attribute name="shortdescription" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="optionexpression" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="implementation"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&gt;
 *             &lt;enumeration value="AnalogToDigital"/&gt;
 *             &lt;enumeration value="DigitalToAnalog"/&gt;
 *             &lt;enumeration value="MixedSignal"/&gt;
 *             &lt;enumeration value="Sensor"/&gt;
 *             &lt;enumeration value="Actuator"/&gt;
 *             &lt;enumeration value="Other"/&gt;
 *             &lt;enumeration value="PWRVoltage"/&gt;
 *             &lt;enumeration value="Supply"/&gt;
 *             &lt;enumeration value="Ground"/&gt;
 *             &lt;enumeration value="AUTOSAR"/&gt;
 *             &lt;enumeration value="C"/&gt;
 *             &lt;enumeration value="MatLab"/&gt;
 *             &lt;enumeration value="SystemC"/&gt;
 *             &lt;enumeration value="UML"/&gt;
 *             &lt;enumeration value="NotSet"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="maximumlatency" type="{http://www.w3.org/2001/XMLSchema}double" /&gt;
 *       &lt;attribute name="powerconsumption" type="{http://www.w3.org/2001/XMLSchema}double" /&gt;
 *       &lt;attribute name="frequency" type="{http://www.w3.org/2001/XMLSchema}double" /&gt;
 *       &lt;attribute name="runtime" type="{http://www.w3.org/2001/XMLSchema}double" /&gt;
 *       &lt;attribute name="thermaloutput" type="{http://www.w3.org/2001/XMLSchema}double" /&gt;
 *       &lt;attribute name="type"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&gt;
 *             &lt;enumeration value="Driver"/&gt;
 *             &lt;enumeration value="Hardware"/&gt;
 *             &lt;enumeration value="Power"/&gt;
 *             &lt;enumeration value="Software"/&gt;
 *             &lt;enumeration value="NotSet"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="cpu" type="{http://www.w3.org/2001/XMLSchema}double" /&gt;
 *       &lt;attribute name="rom" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *       &lt;attribute name="flash" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *       &lt;attribute name="ram" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *       &lt;attribute name="volume" type="{http://www.w3.org/2001/XMLSchema}double" /&gt;
 *       &lt;attribute name="sectionalarea" type="{http://www.w3.org/2001/XMLSchema}double" /&gt;
 *       &lt;attribute name="weight" type="{http://www.w3.org/2001/XMLSchema}double" /&gt;
 *       &lt;attribute name="role" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="designid" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="partnumber" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FunctionType", propOrder = {
    "portOrProperty"
})
public class FunctionType {

    @XmlElements({
        @XmlElement(name = "port", type = FunctionType.Port.class),
        @XmlElement(name = "property", type = BasePropertyType.class)
    })
    protected List<Object> portOrProperty;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "architecturalCost")
    protected Double architecturalCost;
    @XmlAttribute(name = "shortdescription")
    protected String shortdescription;
    @XmlAttribute(name = "optionexpression")
    protected String optionexpression;
    @XmlAttribute(name = "implementation")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String implementation;
    @XmlAttribute(name = "maximumlatency")
    protected Double maximumlatency;
    @XmlAttribute(name = "powerconsumption")
    protected Double powerconsumption;
    @XmlAttribute(name = "frequency")
    protected Double frequency;
    @XmlAttribute(name = "runtime")
    protected Double runtime;
    @XmlAttribute(name = "thermaloutput")
    protected Double thermaloutput;
    @XmlAttribute(name = "type")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String type;
    @XmlAttribute(name = "cpu")
    protected Double cpu;
    @XmlAttribute(name = "rom")
    protected Integer rom;
    @XmlAttribute(name = "flash")
    protected Integer flash;
    @XmlAttribute(name = "ram")
    protected Integer ram;
    @XmlAttribute(name = "volume")
    protected Double volume;
    @XmlAttribute(name = "sectionalarea")
    protected Double sectionalarea;
    @XmlAttribute(name = "weight")
    protected Double weight;
    @XmlAttribute(name = "role")
    protected String role;
    @XmlAttribute(name = "designid")
    protected String designid;
    @XmlAttribute(name = "partnumber")
    protected String partnumber;
    @XmlAttribute(name = "symbol")
    protected String symbol;
    @XmlAttribute(name = "symbollibrary")
    protected String symbollibrary;

    /**
     * Gets the value of the portOrProperty property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the portOrProperty property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPortOrProperty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FunctionType.Port }
     * {@link BasePropertyType }
     * 
     * 
     */
    public List<Object> getPortOrProperty() {
        if (portOrProperty == null) {
            portOrProperty = new ArrayList<Object>();
        }
        return this.portOrProperty;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the architecturalCost property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getArchitecturalCost() {
        return architecturalCost;
    }

    /**
     * Sets the value of the architecturalCost property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setArchitecturalCost(Double value) {
        this.architecturalCost = value;
    }

    /**
     * Gets the value of the shortdescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShortdescription() {
        return shortdescription;
    }

    /**
     * Sets the value of the shortdescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShortdescription(String value) {
        this.shortdescription = value;
    }

    /**
     * Gets the value of the optionexpression property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOptionexpression() {
        return optionexpression;
    }

    /**
     * Sets the value of the optionexpression property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOptionexpression(String value) {
        this.optionexpression = value;
    }

    /**
     * Gets the value of the implementation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImplementation() {
        return implementation;
    }

    /**
     * Sets the value of the implementation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImplementation(String value) {
        this.implementation = value;
    }

    /**
     * Gets the value of the maximumlatency property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMaximumlatency() {
        return maximumlatency;
    }

    /**
     * Sets the value of the maximumlatency property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMaximumlatency(Double value) {
        this.maximumlatency = value;
    }

    /**
     * Gets the value of the powerconsumption property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPowerconsumption() {
        return powerconsumption;
    }

    /**
     * Sets the value of the powerconsumption property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPowerconsumption(Double value) {
        this.powerconsumption = value;
    }

    /**
     * Gets the value of the frequency property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getFrequency() {
        return frequency;
    }

    /**
     * Sets the value of the frequency property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setFrequency(Double value) {
        this.frequency = value;
    }

    /**
     * Gets the value of the runtime property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getRuntime() {
        return runtime;
    }

    /**
     * Sets the value of the runtime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setRuntime(Double value) {
        this.runtime = value;
    }

    /**
     * Gets the value of the thermaloutput property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getThermaloutput() {
        return thermaloutput;
    }

    /**
     * Sets the value of the thermaloutput property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setThermaloutput(Double value) {
        this.thermaloutput = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the cpu property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getCpu() {
        return cpu;
    }

    /**
     * Sets the value of the cpu property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setCpu(Double value) {
        this.cpu = value;
    }

    /**
     * Gets the value of the rom property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRom() {
        return rom;
    }

    /**
     * Sets the value of the rom property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRom(Integer value) {
        this.rom = value;
    }

    /**
     * Gets the value of the flash property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getFlash() {
        return flash;
    }

    /**
     * Sets the value of the flash property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setFlash(Integer value) {
        this.flash = value;
    }

    /**
     * Gets the value of the ram property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRam() {
        return ram;
    }

    /**
     * Sets the value of the ram property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRam(Integer value) {
        this.ram = value;
    }

    /**
     * Gets the value of the volume property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getVolume() {
        return volume;
    }

    /**
     * Sets the value of the volume property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setVolume(Double value) {
        this.volume = value;
    }

    /**
     * Gets the value of the sectionalarea property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getSectionalarea() {
        return sectionalarea;
    }

    /**
     * Sets the value of the sectionalarea property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setSectionalarea(Double value) {
        this.sectionalarea = value;
    }

    /**
     * Gets the value of the weight property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getWeight() {
        return weight;
    }

    /**
     * Sets the value of the weight property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setWeight(Double value) {
        this.weight = value;
    }

    /**
     * Gets the value of the role property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRole() {
        return role;
    }

    /**
     * Sets the value of the role property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRole(String value) {
        this.role = value;
    }

    /**
     * Gets the value of the designid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDesignid() {
        return designid;
    }

    /**
     * Sets the value of the designid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDesignid(String value) {
        this.designid = value;
    }

    /**
     * Gets the value of the partnumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartnumber() {
        return partnumber;
    }

    /**
     * Sets the value of the partnumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartnumber(String value) {
        this.partnumber = value;
    }

    /**
     * Gets the value of the symbol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSymbol() {
        return symbol;
    }

    /**
     * Sets the value of the symbol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSymbol(String value) {
        this.symbol = value;
    }

    /**
     * Gets the value of the symbollibrary property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSymbollibrary() {
        return symbollibrary;
    }

    /**
     * Sets the value of the symbollibrary property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSymbollibrary(String value) {
        this.symbollibrary = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;extension base="{http://www.mentor.com/harness/Schema/bridgesharness}PortType"&gt;
     *     &lt;/extension&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Port
        extends PortType
    {


    }

}
