//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.21 at 09:49:19 PM AEDT 
//


package com.mentor.harness.schema.bridgesharness;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElements;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 *                     Root element type definition for the exchange of harness design data.
 *                     It can contain a plane (used for the 3D flattening), a physical harness description and the electrical harness description.
 *                 
 * 
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *         &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;element name="source" type="{http://www.mentor.com/harness/Schema/bridgesharness}SourceFileType" minOccurs="0"/&gt;
 *           &lt;element name="optionset" type="{http://www.mentor.com/harness/Schema/bridgesharness}BaseOptionSetType" minOccurs="0"/&gt;
 *           &lt;element name="modulecodeset" minOccurs="0"&gt;
 *             &lt;complexType&gt;
 *               &lt;complexContent&gt;
 *                 &lt;extension base="{http://www.mentor.com/harness/Schema/bridgesharness}BaseModuleCodeSetType"&gt;
 *                   &lt;attribute name="functionalmodulecodelevel"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&gt;
 *                         &lt;enumeration value="design"/&gt;
 *                         &lt;enumeration value="project"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/attribute&gt;
 *                   &lt;attribute name="productionmodulecodelevel"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&gt;
 *                         &lt;enumeration value="design"/&gt;
 *                         &lt;enumeration value="project"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/attribute&gt;
 *                 &lt;/extension&gt;
 *               &lt;/complexContent&gt;
 *             &lt;/complexType&gt;
 *           &lt;/element&gt;
 *           &lt;element name="productionmodulecodehierarchy" minOccurs="0"&gt;
 *             &lt;complexType&gt;
 *               &lt;complexContent&gt;
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                   &lt;sequence maxOccurs="unbounded" minOccurs="0"&gt;
 *                     &lt;element name="modulecodehierarchy" minOccurs="0"&gt;
 *                       &lt;complexType&gt;
 *                         &lt;complexContent&gt;
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                             &lt;attribute name="childref" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                             &lt;attribute name="parentref" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                           &lt;/restriction&gt;
 *                         &lt;/complexContent&gt;
 *                       &lt;/complexType&gt;
 *                     &lt;/element&gt;
 *                   &lt;/sequence&gt;
 *                 &lt;/restriction&gt;
 *               &lt;/complexContent&gt;
 *             &lt;/complexType&gt;
 *           &lt;/element&gt;
 *           &lt;element name="plane" minOccurs="0"&gt;
 *             &lt;complexType&gt;
 *               &lt;complexContent&gt;
 *                 &lt;extension base="{http://www.mentor.com/harness/Schema/bridgesharness}PlaneType"&gt;
 *                 &lt;/extension&gt;
 *               &lt;/complexContent&gt;
 *             &lt;/complexType&gt;
 *           &lt;/element&gt;
 *         &lt;/choice&gt;
 *         &lt;sequence&gt;
 *           &lt;element name="harness" type="{http://www.mentor.com/harness/Schema/bridgesharness}HarnessDataType" minOccurs="0"/&gt;
 *           &lt;element name="wiringconnectivity" type="{http://www.mentor.com/harness/Schema/bridgesharness}WiringDesignType" minOccurs="0"/&gt;
 *           &lt;element name="constraintsholder" type="{http://www.mentor.com/harness/Schema/bridgesharness}ConstraintsElementType" minOccurs="0"/&gt;
 *         &lt;/sequence&gt;
 *       &lt;/choice&gt;
 *       &lt;attGroup ref="{http://www.mentor.com/harness/Schema/bridgesharness}RootElementCommonAttributes"/&gt;
 *       &lt;attribute name="author" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="state" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sourceOrOptionsetOrModulecodeset"
})
@XmlRootElement(name = "harnessdesign")
public class Harnessdesign {

    @XmlElements({
        @XmlElement(name = "source", type = SourceFileType.class),
        @XmlElement(name = "optionset", type = BaseOptionSetType.class),
        @XmlElement(name = "modulecodeset", type = Harnessdesign.Modulecodeset.class),
        @XmlElement(name = "productionmodulecodehierarchy", type = Harnessdesign.Productionmodulecodehierarchy.class),
        @XmlElement(name = "plane", type = Harnessdesign.Plane.class),
        @XmlElement(name = "harness", type = HarnessDataType.class),
        @XmlElement(name = "wiringconnectivity", type = WiringDesignType.class),
        @XmlElement(name = "constraintsholder", type = ConstraintsElementType.class)
    })
    protected List<Object> sourceOrOptionsetOrModulecodeset;
    @XmlAttribute(name = "author")
    protected String author;
    @XmlAttribute(name = "state")
    protected String state;
    @XmlAttribute(name = "designtype")
    protected String designtype;
    @XmlAttribute(name = "originsystem")
    protected String originsystem;
    @XmlAttribute(name = "id")
    protected String id;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "revision")
    protected String revision;
    @XmlAttribute(name = "shortdesc")
    protected String shortdesc;
    @XmlAttribute(name = "partnumber")
    protected String partnumber;
    @XmlAttribute(name = "projectid")
    protected String projectid;
    @XmlAttribute(name = "projectname")
    protected String projectname;
    @XmlAttribute(name = "projectdesc")
    protected String projectdesc;

    /**
     * Gets the value of the sourceOrOptionsetOrModulecodeset property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the sourceOrOptionsetOrModulecodeset property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSourceOrOptionsetOrModulecodeset().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SourceFileType }
     * {@link BaseOptionSetType }
     * {@link Harnessdesign.Modulecodeset }
     * {@link Harnessdesign.Productionmodulecodehierarchy }
     * {@link Harnessdesign.Plane }
     * {@link HarnessDataType }
     * {@link WiringDesignType }
     * {@link ConstraintsElementType }
     * 
     * 
     */
    public List<Object> getSourceOrOptionsetOrModulecodeset() {
        if (sourceOrOptionsetOrModulecodeset == null) {
            sourceOrOptionsetOrModulecodeset = new ArrayList<Object>();
        }
        return this.sourceOrOptionsetOrModulecodeset;
    }

    /**
     * Gets the value of the author property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthor() {
        return author;
    }

    /**
     * Sets the value of the author property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthor(String value) {
        this.author = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setState(String value) {
        this.state = value;
    }

    /**
     * Gets the value of the designtype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDesigntype() {
        return designtype;
    }

    /**
     * Sets the value of the designtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDesigntype(String value) {
        this.designtype = value;
    }

    /**
     * Gets the value of the originsystem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginsystem() {
        return originsystem;
    }

    /**
     * Sets the value of the originsystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginsystem(String value) {
        this.originsystem = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the revision property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRevision() {
        return revision;
    }

    /**
     * Sets the value of the revision property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRevision(String value) {
        this.revision = value;
    }

    /**
     * Gets the value of the shortdesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShortdesc() {
        return shortdesc;
    }

    /**
     * Sets the value of the shortdesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShortdesc(String value) {
        this.shortdesc = value;
    }

    /**
     * Gets the value of the partnumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartnumber() {
        return partnumber;
    }

    /**
     * Sets the value of the partnumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartnumber(String value) {
        this.partnumber = value;
    }

    /**
     * Gets the value of the projectid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProjectid() {
        return projectid;
    }

    /**
     * Sets the value of the projectid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProjectid(String value) {
        this.projectid = value;
    }

    /**
     * Gets the value of the projectname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProjectname() {
        return projectname;
    }

    /**
     * Sets the value of the projectname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProjectname(String value) {
        this.projectname = value;
    }

    /**
     * Gets the value of the projectdesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProjectdesc() {
        return projectdesc;
    }

    /**
     * Sets the value of the projectdesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProjectdesc(String value) {
        this.projectdesc = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;extension base="{http://www.mentor.com/harness/Schema/bridgesharness}BaseModuleCodeSetType"&gt;
     *       &lt;attribute name="functionalmodulecodelevel"&gt;
     *         &lt;simpleType&gt;
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&gt;
     *             &lt;enumeration value="design"/&gt;
     *             &lt;enumeration value="project"/&gt;
     *           &lt;/restriction&gt;
     *         &lt;/simpleType&gt;
     *       &lt;/attribute&gt;
     *       &lt;attribute name="productionmodulecodelevel"&gt;
     *         &lt;simpleType&gt;
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&gt;
     *             &lt;enumeration value="design"/&gt;
     *             &lt;enumeration value="project"/&gt;
     *           &lt;/restriction&gt;
     *         &lt;/simpleType&gt;
     *       &lt;/attribute&gt;
     *     &lt;/extension&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Modulecodeset
        extends BaseModuleCodeSetType
    {

        @XmlAttribute(name = "functionalmodulecodelevel")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String functionalmodulecodelevel;
        @XmlAttribute(name = "productionmodulecodelevel")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String productionmodulecodelevel;

        /**
         * Gets the value of the functionalmodulecodelevel property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFunctionalmodulecodelevel() {
            return functionalmodulecodelevel;
        }

        /**
         * Sets the value of the functionalmodulecodelevel property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFunctionalmodulecodelevel(String value) {
            this.functionalmodulecodelevel = value;
        }

        /**
         * Gets the value of the productionmodulecodelevel property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProductionmodulecodelevel() {
            return productionmodulecodelevel;
        }

        /**
         * Sets the value of the productionmodulecodelevel property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProductionmodulecodelevel(String value) {
            this.productionmodulecodelevel = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;extension base="{http://www.mentor.com/harness/Schema/bridgesharness}PlaneType"&gt;
     *     &lt;/extension&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Plane
        extends PlaneType
    {


    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0"&gt;
     *         &lt;element name="modulecodehierarchy" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;attribute name="childref" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                 &lt;attribute name="parentref" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "modulecodehierarchy"
    })
    public static class Productionmodulecodehierarchy {

        protected List<Harnessdesign.Productionmodulecodehierarchy.Modulecodehierarchy> modulecodehierarchy;

        /**
         * Gets the value of the modulecodehierarchy property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the modulecodehierarchy property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getModulecodehierarchy().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Harnessdesign.Productionmodulecodehierarchy.Modulecodehierarchy }
         * 
         * 
         */
        public List<Harnessdesign.Productionmodulecodehierarchy.Modulecodehierarchy> getModulecodehierarchy() {
            if (modulecodehierarchy == null) {
                modulecodehierarchy = new ArrayList<Harnessdesign.Productionmodulecodehierarchy.Modulecodehierarchy>();
            }
            return this.modulecodehierarchy;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;attribute name="childref" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *       &lt;attribute name="parentref" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Modulecodehierarchy {

            @XmlAttribute(name = "childref", required = true)
            protected String childref;
            @XmlAttribute(name = "parentref", required = true)
            protected String parentref;

            /**
             * Gets the value of the childref property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getChildref() {
                return childref;
            }

            /**
             * Sets the value of the childref property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setChildref(String value) {
                this.childref = value;
            }

            /**
             * Gets the value of the parentref property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getParentref() {
                return parentref;
            }

            /**
             * Sets the value of the parentref property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setParentref(String value) {
                this.parentref = value;
            }

        }

    }

}
