//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.21 at 09:49:19 PM AEDT 
//


package com.mentor.harness.schema.bridgesharness;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElements;
import jakarta.xml.bind.annotation.XmlID;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for MessageType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MessageType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *         &lt;element name="connection"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;extension base="{http://www.mentor.com/harness/Schema/bridgesharness}SignalConnectionType"&gt;
 *               &lt;/extension&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="messagesignal" type="{http://www.mentor.com/harness/Schema/bridgesharness}SignalType"/&gt;
 *         &lt;element name="property" type="{http://www.mentor.com/harness/Schema/bridgesharness}BasePropertyType"/&gt;
 *         &lt;element name="extendedattribute"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;extension base="{http://www.mentor.com/harness/Schema/bridgesharness}ExtendedAttributeType"&gt;
 *               &lt;/extension&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/choice&gt;
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" /&gt;
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="OTI" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="OTIV" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="MessageInstance" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="bitsize" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *       &lt;attribute name="multiplexed" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="maximumlatency" type="{http://www.w3.org/2001/XMLSchema}double" /&gt;
 *       &lt;attribute name="maximiumage" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *       &lt;attribute name="frequency" type="{http://www.w3.org/2001/XMLSchema}double" /&gt;
 *       &lt;attribute name="shortdescription" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="optionexpression" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="implementation"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&gt;
 *             &lt;enumeration value="Bluetooth"/&gt;
 *             &lt;enumeration value="WiFi"/&gt;
 *             &lt;enumeration value="ThreeG"/&gt;
 *             &lt;enumeration value="CanHi"/&gt;
 *             &lt;enumeration value="CanLo"/&gt;
 *             &lt;enumeration value="Ethernet"/&gt;
 *             &lt;enumeration value="Flexray"/&gt;
 *             &lt;enumeration value="LIN"/&gt;
 *             &lt;enumeration value="J1939"/&gt;
 *             &lt;enumeration value="ISOBUS"/&gt;
 *             &lt;enumeration value="MOST25"/&gt;
 *             &lt;enumeration value="MOST50"/&gt;
 *             &lt;enumeration value="MOST150"/&gt;
 *             &lt;enumeration value="NotSet"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="type"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&gt;
 *             &lt;enumeration value="RF"/&gt;
 *             &lt;enumeration value="Electrical"/&gt;
 *             &lt;enumeration value="Optical"/&gt;
 *             &lt;enumeration value="Software"/&gt;
 *             &lt;enumeration value="NotSet"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MessageType", propOrder = {
    "connectionOrMessagesignalOrProperty"
})
public class MessageType {

    @XmlElements({
        @XmlElement(name = "connection", type = MessageType.Connection.class),
        @XmlElement(name = "messagesignal", type = SignalType.class),
        @XmlElement(name = "property", type = BasePropertyType.class),
        @XmlElement(name = "extendedattribute", type = MessageType.Extendedattribute.class)
    })
    protected List<Object> connectionOrMessagesignalOrProperty;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "OTI")
    protected String oti;
    @XmlAttribute(name = "OTIV")
    protected String otiv;
    @XmlAttribute(name = "MessageInstance")
    protected String messageInstance;
    @XmlAttribute(name = "bitsize")
    protected Integer bitsize;
    @XmlAttribute(name = "multiplexed")
    protected Boolean multiplexed;
    @XmlAttribute(name = "maximumlatency")
    protected Double maximumlatency;
    @XmlAttribute(name = "maximiumage")
    protected Integer maximiumage;
    @XmlAttribute(name = "frequency")
    protected Double frequency;
    @XmlAttribute(name = "shortdescription")
    protected String shortdescription;
    @XmlAttribute(name = "optionexpression")
    protected String optionexpression;
    @XmlAttribute(name = "implementation")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String implementation;
    @XmlAttribute(name = "type")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String type;

    /**
     * Gets the value of the connectionOrMessagesignalOrProperty property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the connectionOrMessagesignalOrProperty property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConnectionOrMessagesignalOrProperty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MessageType.Connection }
     * {@link SignalType }
     * {@link BasePropertyType }
     * {@link MessageType.Extendedattribute }
     * 
     * 
     */
    public List<Object> getConnectionOrMessagesignalOrProperty() {
        if (connectionOrMessagesignalOrProperty == null) {
            connectionOrMessagesignalOrProperty = new ArrayList<Object>();
        }
        return this.connectionOrMessagesignalOrProperty;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the oti property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOTI() {
        return oti;
    }

    /**
     * Sets the value of the oti property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOTI(String value) {
        this.oti = value;
    }

    /**
     * Gets the value of the otiv property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOTIV() {
        return otiv;
    }

    /**
     * Sets the value of the otiv property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOTIV(String value) {
        this.otiv = value;
    }

    /**
     * Gets the value of the messageInstance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageInstance() {
        return messageInstance;
    }

    /**
     * Sets the value of the messageInstance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageInstance(String value) {
        this.messageInstance = value;
    }

    /**
     * Gets the value of the bitsize property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getBitsize() {
        return bitsize;
    }

    /**
     * Sets the value of the bitsize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setBitsize(Integer value) {
        this.bitsize = value;
    }

    /**
     * Gets the value of the multiplexed property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isMultiplexed() {
        return multiplexed;
    }

    /**
     * Sets the value of the multiplexed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMultiplexed(Boolean value) {
        this.multiplexed = value;
    }

    /**
     * Gets the value of the maximumlatency property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMaximumlatency() {
        return maximumlatency;
    }

    /**
     * Sets the value of the maximumlatency property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMaximumlatency(Double value) {
        this.maximumlatency = value;
    }

    /**
     * Gets the value of the maximiumage property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMaximiumage() {
        return maximiumage;
    }

    /**
     * Sets the value of the maximiumage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaximiumage(Integer value) {
        this.maximiumage = value;
    }

    /**
     * Gets the value of the frequency property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getFrequency() {
        return frequency;
    }

    /**
     * Sets the value of the frequency property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setFrequency(Double value) {
        this.frequency = value;
    }

    /**
     * Gets the value of the shortdescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShortdescription() {
        return shortdescription;
    }

    /**
     * Sets the value of the shortdescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShortdescription(String value) {
        this.shortdescription = value;
    }

    /**
     * Gets the value of the optionexpression property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOptionexpression() {
        return optionexpression;
    }

    /**
     * Sets the value of the optionexpression property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOptionexpression(String value) {
        this.optionexpression = value;
    }

    /**
     * Gets the value of the implementation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImplementation() {
        return implementation;
    }

    /**
     * Sets the value of the implementation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImplementation(String value) {
        this.implementation = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;extension base="{http://www.mentor.com/harness/Schema/bridgesharness}SignalConnectionType"&gt;
     *     &lt;/extension&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Connection
        extends SignalConnectionType
    {


    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;extension base="{http://www.mentor.com/harness/Schema/bridgesharness}ExtendedAttributeType"&gt;
     *     &lt;/extension&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Extendedattribute
        extends ExtendedAttributeType
    {


    }

}
