//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.21 at 09:49:19 PM AEDT 
//


package com.mentor.harness.schema.bridgesharness;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OrientationConstraintType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="OrientationConstraintType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&gt;
 *     &lt;enumeration value="orthogonal"/&gt;
 *     &lt;enumeration value="linear"/&gt;
 *     &lt;enumeration value="co-located"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "OrientationConstraintType")
@XmlEnum
public enum OrientationConstraintType {

    @XmlEnumValue("orthogonal")
    ORTHOGONAL("orthogonal"),
    @XmlEnumValue("linear")
    LINEAR("linear"),
    @XmlEnumValue("co-located")
    CO_LOCATED("co-located");
    private final String value;

    OrientationConstraintType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static OrientationConstraintType fromValue(String v) {
        for (OrientationConstraintType c: OrientationConstraintType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
