//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.21 at 09:49:19 PM AEDT 
//


package com.mentor.harness.schema.bridgesharness;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElements;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 *                 This element is used only in the Capital Integrator Wiring Import flow.
 *                 Specialized connectors are modelled as children of a generalized (regular) connector. In the standard
 *                 Bridges flow, this element is never output:
 *                 specialized connectors are output as regular connectors if the selected harness
 *                 levels are compatible, otherwise, the generalized connector is output.
 *             
 * 
 * <p>Java class for SpecializedConnectorType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SpecializedConnectorType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *         &lt;element name="pin"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;extension base="{http://www.mentor.com/harness/Schema/bridgesharness}SpecializedPinType"&gt;
 *                 &lt;group ref="{http://www.mentor.com/harness/Schema/bridgesharness}CommonElementsGroup"/&gt;
 *               &lt;/extension&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="mating" type="{http://www.mentor.com/harness/Schema/bridgesharness}MatingType"/&gt;
 *         &lt;group ref="{http://www.mentor.com/harness/Schema/bridgesharness}CommonElementsGroup"/&gt;
 *       &lt;/choice&gt;
 *       &lt;attGroup ref="{http://www.mentor.com/harness/Schema/bridgesharness}SupplierPartAttributes"/&gt;
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="partnumber" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="partrevision" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="quantity" type="{http://www.w3.org/2001/XMLSchema}double" /&gt;
 *       &lt;attribute name="architecturalCost" type="{http://www.w3.org/2001/XMLSchema}double" /&gt;
 *       &lt;attribute name="weight" type="{http://www.w3.org/2001/XMLSchema}double" /&gt;
 *       &lt;attribute name="datum" default="front"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&gt;
 *             &lt;enumeration value="front"/&gt;
 *             &lt;enumeration value="back"/&gt;
 *             &lt;enumeration value="terminal"/&gt;
 *             &lt;enumeration value="default"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="backshellOrientation" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="defaultTerminalMaterial" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="keywayOrientation" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="mcadID" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="shortdescription" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="optionexpression" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="harness" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="sealed" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="plugged" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="greased" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="incBom" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="idc" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="backshellPlugged" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="pokeHome" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SpecializedConnectorType", propOrder = {
    "pinOrMatingOrHarnesslevel"
})
public class SpecializedConnectorType {

    @XmlElements({
        @XmlElement(name = "pin", type = SpecializedConnectorType.Pin.class),
        @XmlElement(name = "mating", type = MatingType.class),
        @XmlElement(name = "harnesslevel", type = HarnessLevelType.class),
        @XmlElement(name = "property", type = BasePropertyType.class),
        @XmlElement(name = "variant", type = BaseVarianceType.class),
        @XmlElement(name = "functionalvariant", type = FunctionalVariantType.class),
        @XmlElement(name = "productionvariant", type = ProductionVariantType.class),
        @XmlElement(name = "refedmodule", type = BaseReferredModuleType.class)
    })
    protected List<Object> pinOrMatingOrHarnesslevel;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "id", required = true)
    protected String id;
    @XmlAttribute(name = "partnumber")
    protected String partnumber;
    @XmlAttribute(name = "partrevision")
    protected String partrevision;
    @XmlAttribute(name = "quantity")
    protected Double quantity;
    @XmlAttribute(name = "architecturalCost")
    protected Double architecturalCost;
    @XmlAttribute(name = "weight")
    protected Double weight;
    @XmlAttribute(name = "datum")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String datum;
    @XmlAttribute(name = "backshellOrientation")
    protected String backshellOrientation;
    @XmlAttribute(name = "defaultTerminalMaterial")
    protected String defaultTerminalMaterial;
    @XmlAttribute(name = "keywayOrientation")
    protected String keywayOrientation;
    @XmlAttribute(name = "mcadID")
    protected String mcadID;
    @XmlAttribute(name = "shortdescription")
    protected String shortdescription;
    @XmlAttribute(name = "optionexpression")
    protected String optionexpression;
    @XmlAttribute(name = "harness")
    protected String harness;
    @XmlAttribute(name = "sealed")
    protected Boolean sealed;
    @XmlAttribute(name = "plugged")
    protected Boolean plugged;
    @XmlAttribute(name = "greased")
    protected Boolean greased;
    @XmlAttribute(name = "incBom")
    protected Boolean incBom;
    @XmlAttribute(name = "idc")
    protected Boolean idc;
    @XmlAttribute(name = "backshellPlugged")
    protected Boolean backshellPlugged;
    @XmlAttribute(name = "pokeHome")
    protected Boolean pokeHome;
    @XmlAttribute(name = "supplierpart")
    @XmlSchemaType(name = "anySimpleType")
    protected String supplierpart;
    @XmlAttribute(name = "customerpart")
    @XmlSchemaType(name = "anySimpleType")
    protected String customerpart;

    /**
     * Gets the value of the pinOrMatingOrHarnesslevel property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the pinOrMatingOrHarnesslevel property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPinOrMatingOrHarnesslevel().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SpecializedConnectorType.Pin }
     * {@link MatingType }
     * {@link HarnessLevelType }
     * {@link BasePropertyType }
     * {@link BaseVarianceType }
     * {@link FunctionalVariantType }
     * {@link ProductionVariantType }
     * {@link BaseReferredModuleType }
     * 
     * 
     */
    public List<Object> getPinOrMatingOrHarnesslevel() {
        if (pinOrMatingOrHarnesslevel == null) {
            pinOrMatingOrHarnesslevel = new ArrayList<Object>();
        }
        return this.pinOrMatingOrHarnesslevel;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the partnumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartnumber() {
        return partnumber;
    }

    /**
     * Sets the value of the partnumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartnumber(String value) {
        this.partnumber = value;
    }

    /**
     * Gets the value of the partrevision property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartrevision() {
        return partrevision;
    }

    /**
     * Sets the value of the partrevision property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartrevision(String value) {
        this.partrevision = value;
    }

    /**
     * Gets the value of the quantity property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getQuantity() {
        return quantity;
    }

    /**
     * Sets the value of the quantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setQuantity(Double value) {
        this.quantity = value;
    }

    /**
     * Gets the value of the architecturalCost property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getArchitecturalCost() {
        return architecturalCost;
    }

    /**
     * Sets the value of the architecturalCost property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setArchitecturalCost(Double value) {
        this.architecturalCost = value;
    }

    /**
     * Gets the value of the weight property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getWeight() {
        return weight;
    }

    /**
     * Sets the value of the weight property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setWeight(Double value) {
        this.weight = value;
    }

    /**
     * Gets the value of the datum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatum() {
        if (datum == null) {
            return "front";
        } else {
            return datum;
        }
    }

    /**
     * Sets the value of the datum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatum(String value) {
        this.datum = value;
    }

    /**
     * Gets the value of the backshellOrientation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBackshellOrientation() {
        return backshellOrientation;
    }

    /**
     * Sets the value of the backshellOrientation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBackshellOrientation(String value) {
        this.backshellOrientation = value;
    }

    /**
     * Gets the value of the defaultTerminalMaterial property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultTerminalMaterial() {
        return defaultTerminalMaterial;
    }

    /**
     * Sets the value of the defaultTerminalMaterial property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultTerminalMaterial(String value) {
        this.defaultTerminalMaterial = value;
    }

    /**
     * Gets the value of the keywayOrientation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKeywayOrientation() {
        return keywayOrientation;
    }

    /**
     * Sets the value of the keywayOrientation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKeywayOrientation(String value) {
        this.keywayOrientation = value;
    }

    /**
     * Gets the value of the mcadID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMcadID() {
        return mcadID;
    }

    /**
     * Sets the value of the mcadID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMcadID(String value) {
        this.mcadID = value;
    }

    /**
     * Gets the value of the shortdescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShortdescription() {
        return shortdescription;
    }

    /**
     * Sets the value of the shortdescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShortdescription(String value) {
        this.shortdescription = value;
    }

    /**
     * Gets the value of the optionexpression property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOptionexpression() {
        return optionexpression;
    }

    /**
     * Sets the value of the optionexpression property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOptionexpression(String value) {
        this.optionexpression = value;
    }

    /**
     * Gets the value of the harness property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHarness() {
        return harness;
    }

    /**
     * Sets the value of the harness property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHarness(String value) {
        this.harness = value;
    }

    /**
     * Gets the value of the sealed property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSealed() {
        return sealed;
    }

    /**
     * Sets the value of the sealed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSealed(Boolean value) {
        this.sealed = value;
    }

    /**
     * Gets the value of the plugged property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPlugged() {
        return plugged;
    }

    /**
     * Sets the value of the plugged property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPlugged(Boolean value) {
        this.plugged = value;
    }

    /**
     * Gets the value of the greased property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isGreased() {
        return greased;
    }

    /**
     * Sets the value of the greased property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setGreased(Boolean value) {
        this.greased = value;
    }

    /**
     * Gets the value of the incBom property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIncBom() {
        return incBom;
    }

    /**
     * Sets the value of the incBom property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIncBom(Boolean value) {
        this.incBom = value;
    }

    /**
     * Gets the value of the idc property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIdc() {
        return idc;
    }

    /**
     * Sets the value of the idc property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIdc(Boolean value) {
        this.idc = value;
    }

    /**
     * Gets the value of the backshellPlugged property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isBackshellPlugged() {
        return backshellPlugged;
    }

    /**
     * Sets the value of the backshellPlugged property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBackshellPlugged(Boolean value) {
        this.backshellPlugged = value;
    }

    /**
     * Gets the value of the pokeHome property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPokeHome() {
        return pokeHome;
    }

    /**
     * Sets the value of the pokeHome property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPokeHome(Boolean value) {
        this.pokeHome = value;
    }

    /**
     * Gets the value of the supplierpart property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupplierpart() {
        return supplierpart;
    }

    /**
     * Sets the value of the supplierpart property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupplierpart(String value) {
        this.supplierpart = value;
    }

    /**
     * Gets the value of the customerpart property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerpart() {
        return customerpart;
    }

    /**
     * Sets the value of the customerpart property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerpart(String value) {
        this.customerpart = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;extension base="{http://www.mentor.com/harness/Schema/bridgesharness}SpecializedPinType"&gt;
     *       &lt;group ref="{http://www.mentor.com/harness/Schema/bridgesharness}CommonElementsGroup"/&gt;
     *     &lt;/extension&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "harnesslevel",
        "propertyGroup"
    })
    public static class Pin
        extends SpecializedPinType
    {

        protected List<HarnessLevelType> harnesslevel;
        @XmlElements({
            @XmlElement(name = "property", type = BasePropertyType.class),
            @XmlElement(name = "variant", type = BaseVarianceType.class),
            @XmlElement(name = "functionalvariant", type = FunctionalVariantType.class),
            @XmlElement(name = "productionvariant", type = ProductionVariantType.class),
            @XmlElement(name = "refedmodule", type = BaseReferredModuleType.class)
        })
        protected List<Object> propertyGroup;

        /**
         * Gets the value of the harnesslevel property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the harnesslevel property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getHarnesslevel().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link HarnessLevelType }
         * 
         * 
         */
        public List<HarnessLevelType> getHarnesslevel() {
            if (harnesslevel == null) {
                harnesslevel = new ArrayList<HarnessLevelType>();
            }
            return this.harnesslevel;
        }

        /**
         * Gets the value of the propertyGroup property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the propertyGroup property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPropertyGroup().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link BasePropertyType }
         * {@link BaseVarianceType }
         * {@link FunctionalVariantType }
         * {@link ProductionVariantType }
         * {@link BaseReferredModuleType }
         * 
         * 
         */
        public List<Object> getPropertyGroup() {
            if (propertyGroup == null) {
                propertyGroup = new ArrayList<Object>();
            }
            return this.propertyGroup;
        }

    }

}
