//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.21 at 09:49:19 PM AEDT 
//


package com.mentor.harness.schema.bridgesharness;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 *                 Represents the extremity of a sub-segment of a bundle.
 *                 As such, it can represent a node, in which case its identifier will be either "start" or "end" to determine the node of the parent bundle.
 *                 Otherwise, the identifier must be unique within the parent bundle and its alphanumerical lexical order indicates its order from start to end node of the parent bundle.
 *                 The direction is the tangent of the bundle curve at this point and must be oriented from start to end node - i.e. curve parameterization must be such that parameter
 *                 at start node is smaller than parameter at end node.
 *             
 * 
 * <p>Java class for WayPointType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WayPointType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Position" type="{http://www.mentor.com/harness/Schema/bridgesharness}CartesianPointType" minOccurs="0"/&gt;
 *         &lt;element name="PlanarPosition" type="{http://www.mentor.com/harness/Schema/bridgesharness}CartesianPointType" minOccurs="0"/&gt;
 *         &lt;element name="Direction" type="{http://www.mentor.com/harness/Schema/bridgesharness}Cartesian3DCoordinate" minOccurs="0"/&gt;
 *         &lt;element name="ElevatedPosition" type="{http://www.mentor.com/harness/Schema/bridgesharness}Cartesian3DCoordinate" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WayPointType", propOrder = {
    "position",
    "planarPosition",
    "direction",
    "elevatedPosition"
})
public class WayPointType {

    @XmlElement(name = "Position")
    protected CartesianPointType position;
    @XmlElement(name = "PlanarPosition")
    protected CartesianPointType planarPosition;
    @XmlElement(name = "Direction")
    protected Cartesian3DCoordinate direction;
    @XmlElement(name = "ElevatedPosition")
    protected Cartesian3DCoordinate elevatedPosition;
    @XmlAttribute(name = "id", required = true)
    protected String id;

    /**
     * Gets the value of the position property.
     * 
     * @return
     *     possible object is
     *     {@link CartesianPointType }
     *     
     */
    public CartesianPointType getPosition() {
        return position;
    }

    /**
     * Sets the value of the position property.
     * 
     * @param value
     *     allowed object is
     *     {@link CartesianPointType }
     *     
     */
    public void setPosition(CartesianPointType value) {
        this.position = value;
    }

    /**
     * Gets the value of the planarPosition property.
     * 
     * @return
     *     possible object is
     *     {@link CartesianPointType }
     *     
     */
    public CartesianPointType getPlanarPosition() {
        return planarPosition;
    }

    /**
     * Sets the value of the planarPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link CartesianPointType }
     *     
     */
    public void setPlanarPosition(CartesianPointType value) {
        this.planarPosition = value;
    }

    /**
     * Gets the value of the direction property.
     * 
     * @return
     *     possible object is
     *     {@link Cartesian3DCoordinate }
     *     
     */
    public Cartesian3DCoordinate getDirection() {
        return direction;
    }

    /**
     * Sets the value of the direction property.
     * 
     * @param value
     *     allowed object is
     *     {@link Cartesian3DCoordinate }
     *     
     */
    public void setDirection(Cartesian3DCoordinate value) {
        this.direction = value;
    }

    /**
     * Gets the value of the elevatedPosition property.
     * 
     * @return
     *     possible object is
     *     {@link Cartesian3DCoordinate }
     *     
     */
    public Cartesian3DCoordinate getElevatedPosition() {
        return elevatedPosition;
    }

    /**
     * Sets the value of the elevatedPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link Cartesian3DCoordinate }
     *     
     */
    public void setElevatedPosition(Cartesian3DCoordinate value) {
        this.elevatedPosition = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
