//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.21 at 09:49:19 PM AEDT 
//


package com.mentor.harness.schema.bridgesharness;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElements;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 *                 Main element to model the electrical components in the harness.
 *             
 * 
 * <p>Java class for WiringDesignType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WiringDesignType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *         &lt;element name="device" type="{http://www.mentor.com/harness/Schema/bridgesharness}DeviceType"/&gt;
 *         &lt;element name="splice" type="{http://www.mentor.com/harness/Schema/bridgesharness}SpliceType"/&gt;
 *         &lt;element name="connector" type="{http://www.mentor.com/harness/Schema/bridgesharness}ConnectorType"/&gt;
 *         &lt;element name="net" type="{http://www.mentor.com/harness/Schema/bridgesharness}NetType"/&gt;
 *         &lt;element name="wire" type="{http://www.mentor.com/harness/Schema/bridgesharness}HarnessWireType"/&gt;
 *         &lt;element name="multicore" type="{http://www.mentor.com/harness/Schema/bridgesharness}MulticoreType"/&gt;
 *         &lt;element name="shieldconductor" type="{http://www.mentor.com/harness/Schema/bridgesharness}HarnessShieldType"/&gt;
 *         &lt;element name="shell" type="{http://www.mentor.com/harness/Schema/bridgesharness}ShellType"/&gt;
 *         &lt;element name="assembly" type="{http://www.mentor.com/harness/Schema/bridgesharness}HarnessAssemblyType"/&gt;
 *       &lt;/choice&gt;
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WiringDesignType", propOrder = {
    "deviceOrSpliceOrConnector"
})
public class WiringDesignType {

    @XmlElements({
        @XmlElement(name = "device", type = DeviceType.class),
        @XmlElement(name = "splice", type = SpliceType.class),
        @XmlElement(name = "connector", type = ConnectorType.class),
        @XmlElement(name = "net", type = NetType.class),
        @XmlElement(name = "wire", type = HarnessWireType.class),
        @XmlElement(name = "multicore", type = MulticoreType.class),
        @XmlElement(name = "shieldconductor", type = HarnessShieldType.class),
        @XmlElement(name = "shell", type = ShellType.class),
        @XmlElement(name = "assembly", type = HarnessAssemblyType.class)
    })
    protected List<Object> deviceOrSpliceOrConnector;
    @XmlAttribute(name = "id")
    protected String id;
    @XmlAttribute(name = "name")
    protected String name;

    /**
     * Gets the value of the deviceOrSpliceOrConnector property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the deviceOrSpliceOrConnector property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDeviceOrSpliceOrConnector().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DeviceType }
     * {@link SpliceType }
     * {@link ConnectorType }
     * {@link NetType }
     * {@link HarnessWireType }
     * {@link MulticoreType }
     * {@link HarnessShieldType }
     * {@link ShellType }
     * {@link HarnessAssemblyType }
     * 
     * 
     */
    public List<Object> getDeviceOrSpliceOrConnector() {
        if (deviceOrSpliceOrConnector == null) {
            deviceOrSpliceOrConnector = new ArrayList<Object>();
        }
        return this.deviceOrSpliceOrConnector;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
